### ISSUE TITLE
Modul lässt sich nicht ordnungsgemäß installieren

### ISSUE THREAD

**Issue by m-werk** [heimrichhannot/contao-email2username-bundle#3]
Hallo, ich wollte jetzt auch dieses Modul installieren, aber anscheinend gibt's hier auch nen Fehler. 

Folgendes.
Wenn ich dieses Modul über den CM installiere, funktioniert zwar alles, aber es wird mir die Version 1.2.4 installiert und nicht die 1.2.6. 
Die Installation läuft ohne Fehler durch, aber dafür funktioniert Contao nicht mehr. Ich kann mich im BE nicht anmelden, ich kann auch kein DB-Update durchführen und im Frontend geht auch nichts. Es kommt immer NUR EINE WEISSE SEITE.

Der CM sagt mir, dass es ein Update auf 1.2.6 gibt. Wenn ich dies ausführe, passiert nichts. Es wird KEIN update installiert und ich hab hier weiterhin die Version 1.2.4 und mein Contao zeigt nur eine Weiße seite.

Meine Contao Version: 4.11.1
PHP-Version: 7.4

**Comment by Defcon0** [comment]
In 1.2.5 kamen Abhängigkeiten dazu, die genutzt, aber noch nicht in der composer.json waren (siehe Changelog). Diese musst du dann auch installieren bzw. updaten.

Contao 4.11 Support schaue ich mir fix an.

**Comment by Defcon0** [comment]
OK, soeben erfolgreich installiert in Contao 4.11. Es liegt an der utils-bundle-Abhängigkeit. @koertho hat das gerade gefixt und wenn dein Projekt vorher geupdatet wurde mit Composer, installiert er symfony/config auf 5.x. Dadurch kann dann die gefixte Version vom Utils-Bundle nicht installiert werden, es sei denn, man forcet es.

Füge mal das hier in deine composer.json hinzu und update das ganze Projekt (sofern das geht):

  "heimrichhannot/contao-utils-bundle": "^2.189"

**Comment by m-werk** [comment]
Hallo, hab das in der composer.json hinzugefügt und dann ein Update gestartet via CM. (Hab keinen SSH zugriff)
Das gibt eine große Fehlerliste jetzt. 

`[7.1MiB/0.26s] Loading composer repositories with package information
[57.5MiB/1.81s] Updating dependencies
[1133.9MiB/9.09s] Your requirements could not be resolved to an installable set of packages.
[1133.9MiB/9.09s] 
  Problem 1
    - contao/manager-bundle is locked to version 4.11.1 and an update of this package was not requested.
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.5 (conflict analysis result)
    - contao/manager-bundle 4.11.1 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.4].
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v4.4.1.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v4.4.0.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.47.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.46.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.45.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.44.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.43.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.42.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.41.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.40.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.39.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.38.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.37.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.36.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.35.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.34.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.33.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.32.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.31.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.30.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.29.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.28.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.27.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.26.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.25.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.24.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.23.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.22.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.21.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.20.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.19.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.18.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.17.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.16.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.15.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.14.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.13.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.12.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.11.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.10.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.9.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.8.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.7.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.6.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.5.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.4.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.3.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.2.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.1.
    - contao/manager-bundle 4.11.1 conflicts with symfony/config v3.4.0.
    - Root composer.json requires heimrichhannot/contao-utils-bundle ^2.189 -> satisfiable by heimrichhannot/contao-utils-bundle[2.189.0].
    - heimrichhannot/contao-utils-bundle 2.189.0 requires symfony/config ^3.4|^4.4 -> satisfiable by symfony/config[v3.4.0, ..., v3.4.47, v4.4.0, ..., v4.4.20].
    - symfony/config[v4.4.2, ..., v4.4.20] conflict with symfony/http-kernel v5.2.0.
    - symfony/web-profiler-bundle v5.2.4 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, ..., v5.2.5].
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)
[1133.9MiB/9.10s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[44.6MiB/10.07s] Memory usage: 44.61MB (peak: 1134.89MB), time: 10.08s.
[44.6MiB/10.07s] Finished Composer Cloud resolving.`

**Comment by koertho** [comment]
@m-werk Könntest du es nochmal mit "symfony/config":"^4.4" probieren? Der Contao Manager ist in seinen Möglichkeiten leider sehr eingeschränkt.

**Comment by m-werk** [comment]
Ja, damit hat es funktioniert. Kann ich jetzt wieder symfony auf die 5er version updaten?

**Comment by m-werk** [comment]
Ok, das war wieder ein Schuss in den Ofen. Sobald ich Symfony auf die 5er Update, geht Contao wieder nicht. Alles weiß. 

Ist jetzt für mich vorerst auch egal, hab es anders gelöst.

**Comment by koertho** [comment]
Ja, unsere Erweiterungen sind größtenteils nur Symfony 3 und 4 kompatibel (da wir auch noch Contao 4.4 unterstützen). Dadurch solltest du aber keinen Nachteil haben.
